### ISSUE TITLE
Many thanks for this great tool

### ISSUE THREAD

**Issue by remidomingues** [LukasBudach/jupyter-autodoc#1]
As a data scientist using Jupyter on an everyday basis, many thanks for your contribution!
As a quick pull request review, I couldn't help but notice that this tool, which generates great docstrings, wasn't applied to the [main file](https://github.com/LukasBudach/jupyter-autodoc/blob/main/main.py) :D 

If you REALLY have that much free time, these links might interest you, but I guess you'd really have to be bored to death at home :D
https://jupyterlab.readthedocs.io/en/stable/extension/extension_dev.html
https://aneesha.medium.com/creating-a-jupyter-notebook-extension-part-1-31c72032cad

Looking forward to having you back with us^^

**Comment by LukasBudach** [comment]
Happy to see you like it!

Yea, this is still very rough - I am currently reworking everything regardless, basically tokeninzing python code, as this allows for better overall handling of edge cases and extensibility. And that will also come with tests, which might be nice to have :D

Writing this as a full-on extension sounds really interesting! Although, for now, I will stick with it being separate, until I am happy with the feature-set.

Looking forward to being back!
